### ISSUE TITLE
cppcheck: error: unrecognized command line option: "--max-ctu-depth=4".

### ISSUE THREAD

**Issue by BaderEddineOuaich** [deep5050/cppcheck-action#12]
Hi there, thank you for this useful tool. 
i have an issue while running static analysis task. max_ctu_depth is not recognized
Action: https://github.com/BaderEddineOuaich/Enigma/runs/1455710276
static-analysis.yml file
```yaml
# Enigma Static Analysis task using CppCheck
# https://github.com/marketplace/actions/cppcheck-action
name: static-analysis

# analyse on pushs and pull requests on master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          github_username: "BaderEddineOuaich"
          github_email: "badereddineouaich@gmail.com"
          #commit_msg: "<optional commit message>"
          #check_library:
          #skip_preprocessor:
          enable: warning,portability,performance
          exclude_check: ./Dependencies/
          #inconclusive:
          #inline_suppression:
          force_language: c++
          max_ctu_depth: 4
          #platform: 
          output_file: ./Static-Analysis-Report.txt #(default cppcheck_report.txt)
```
Thank you
