### ISSUE TITLE
feature request: add support for -q option

### ISSUE THREAD

**Issue by nagayev** [deep5050/cppcheck-action#50]
I suggest to add new input option, quite (-q) with default value false.

**Comment by BaderEddineOuaich** [comment]
Hello @nagayev,
You can add any other options you like in the ``other_options:`` field separated with a space.
### Example, let's add two additional options, `--quiet` and `verbose`:
```yaml
name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_library:
          skip_preprocessor:
          enable:
          exclude_check:
          inconclusive:
          inline_suppression:
          force_language:
          force:
          max_ctu_depth:
          platform:
          std:
          output_file:
         other_options: --quiet --verbose

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main' # your branch name goes here
```
I hope this helps, Have a nice day!
