### ISSUE TITLE
Action doesn't run on "Internal" repo

### ISSUE THREAD

**Issue by soumeh01** [deep5050/cppcheck-action#56]
Hi,

I was trying to use this action in my **[internal](https://docs.github.com/en/enterprise-cloud@latest/repositories/creating-and-managing-repositories/about-repositories#about-internal-repositories)** repo. It doesn't work and fails. The action didn't produce any failure logs which I analyze. 

```
Run deep5050/cppcheck-action@main
  with:
    github_token: ***
    enable: performance,portability,unusedFunction
    exclude_check: ./external
    check_library: disable
    skip_preprocessor: disable
    inconclusive: disable
    inline_suppression: disable
    force_language: c++
    force: enable
    max_ctu_depth: 2
    std: c++17
    platform: disable
    other_options: --verbose --std=c++17 -i./tools/test
    output_file: ./cppcheck_report.txt
/usr/bin/docker run --name b5709404637d544838a1844192f95754e_222d44 --label 94351b --workdir /github/workspace --rm -e "INPUT_GITHUB_TOKEN" -e "INPUT_ENABLE" -e "INPUT_EXCLUDE_CHECK" -e "INPUT_CHECK_LIBRARY" -e "INPUT_SKIP_PREPROCESSOR" -e "INPUT_INCONCLUSIVE" -e "INPUT_INLINE_SUPPRESSION" -e "INPUT_FORCE_LANGUAGE" -e "INPUT_FORCE" -e "INPUT_MAX_CTU_DEPTH" -e "INPUT_STD" -e "INPUT_PLATFORM" -e "INPUT_OTHER_OPTIONS" -e "INPUT_OUTPUT_FILE" -e "INPUT_TARGET_BRANCH" -e "INPUT_PULL_REQUEST_BRANCH" -e "INPUT_TARGET_REPOSITORY" -e "INPUT_PULL_REQUEST_REPOSITORY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/devtools-external/devtools-external":"/github/workspace" 94351b:5709404637d544838a1844192f95754e
```

Out of curiosity and to corner the issue, I tried running the same action with the same configurations under **public** repo. It worked seamlessly.
FYI, I ran the action using the highest permissions on the internal repo i.e. `permissions: write-all` just to see if this could be the issue. But no help.

Any input would be highly appreciated.

Thanks
